In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import unicodedata

In [2]:
path = "/content/AHD_english.xlsx"

df = pd.read_excel(
    path,
    engine="openpyxl"
)

df.head()

,Question,Answer,Category
0,"A breast MRI was performed, showing a non-mass...",What is important in the matter is what is the...,General Surgery
1,I suffer from things that force me to do thing...,"Peace be upon you, you need a psychotherapist ...",Psychiatric illness
2,I want to inquire about the complications of b...,"Like other surgical operations, the process of...",Endocrine diseases
3,Today I feel that I have something inside my a...,The condition is most likely to reflect third-...,General Surgery
4,Why do I suddenly feel like I don't know how t...,Possibly organic or a side effect of any medic...,Psychiatric illness

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 808472 entries, 0 to 808471
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Question  808470 non-null  object
 1   Answer    808470 non-null  object
 2   Category  808472 non-null  object
dtypes: object(3)
memory usage: 18.5+ MB

In [4]:
df.isna().sum()

Question    2
Answer      2
Category    0
dtype: int64

In [5]:
for category in ["diabetes", "Endocrine diseases"]:
    if category in df["Category"].values:
        print(f"{category}: Found")
    else:
        print(f"{category}: Not Found")

diabetes: Found
Endocrine diseases: Found

In [6]:
data =[]
for category in ["diabetes", "Endocrine diseases"]:
    for _,row in df.iterrows():
        if row['Category'] == category:
            data.append(row)
df = pd.DataFrame(data)

In [7]:
df['Category'].value_counts()

Category
Endocrine diseases    9237
diabetes              7147
Name: count, dtype: int64

In [8]:
output_path = "/content/AHD_english_cleaned.xlsx"

df.to_excel(
    output_path,
    index=False,
    engine="openpyxl"
)

print(f"Saved successfully: {output_path}")

Saved successfully: /content/AHD_english_cleaned.xlsx

In [9]:
df

,Question,Answer,Category
6629,If the patient enters a diabetic coma and we d...,"Hyperglycemic coma does not occur suddenly, bu...",diabetes
12015,I suffer from dizziness and my blood sugar lev...,"Your safety, God willing. It may be normal due...",diabetes
14653,I am diabetic 2. I take Amaryl 2 ml before foo...,Glycosylated hemoglobin analysis is very impor...,diabetes
15283,"Age 54, normal blood pressure, weight 74, heig...",Who told you that taking B12 is not according ...,diabetes
20096,When I test my blood sugar after fasting for 7...,"Monitor your blood sugar in a laboratory, not ...",diabetes
...,...,...,...
808249,Can hirsutism be an obstacle to pregnancy sinc...,"Hirsutism can be a cause of contraception, but...",Endocrine diseases
808332,"In the name of God, the most gracious, the mos...",What you mentioned in your question constitute...,Endocrine diseases
808335,I have a sister who suffers from hyperthyroidi...,This medicine should not be used during pregna...,Endocrine diseases
808336,I was on duty at the hospital when a woman cam...,The condition goes away with the use of birth ...,Endocrine diseases
808350,Does a mild deficiency in the hormone thyroxin...,This is easy to find out by giving the infant ...,Endocrine diseases

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16384 entries, 6629 to 808350
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Question  16384 non-null  object
 1   Answer    16384 non-null  object
 2   Category  16384 non-null  object
dtypes: object(3)
memory usage: 512.0+ KB

In [11]:
df.isnull().sum()

Question    0
Answer      0
Category    0
dtype: int64

In [12]:
df["Question"] = df["Question"].astype(str).str.strip()
df["Answer"] = df["Answer"].astype(str).str.strip()
df["Category"] = df["Category"].astype(str).str.strip()

In [13]:
df.nunique()

Question    16269
Answer      15419
Category        2
dtype: int64

In [14]:
question_counts = df["Question"].value_counts()

print(question_counts.head(30))

Question
What are the symptoms of diabetes?                                                                                                                                                                                                                         19
What is the treatment for diabetes?                                                                                                                                                                                                                        10
Is there a cure for diabetes?                                                                                                                                                                                                                               7
Symptoms of diabetes                                                                                                                                                                                                                                        5
What is the normal blood sugar level?                                                                                                                                                                                                                       5
What is the best treatment for diabetes?                                                                                                                                                                                                                    3
What is the treatment for low blood sugar?                                                                                                                                                                                                                  3
What are the causes of diabetes?                                                                                                                                                                                                                            3
The best treatment for diabetes                                                                                                                                                                                                                             3
Thyroid symptoms                                                                                                                                                                                                                                            3
What are the symptoms of thyroid disease?                                                                                                                                                                                                                   3
Is there a definitive cure for diabetes?                                                                                                                                                                                                                    3
I suffer from an underactive thyroid gland                                                                                                                                                                                                                  3
What is the treatment for hypothyroidism?                                                                                                                                                                                                                   3
What are the symptoms of thyroid gland?                                                                                                                                                                                                                     3
The latest treatment for diabetes                                                                                                                                                                                                                           3
What is the treatment for thyroid gland?                                                                                                                                                                                                                    3
What is diabetic foot?                                                                                                                                                                                                                                      2
I have been suffering from cancer for a while and recently a diabetic patient. Is there a relationship between the two? What I read is that blood sugar is high in a cancer patient, but the opposite happens and blood sugar is low and...                 2
A cumulative blood sugar test 3 months ago was 6.3, and my weight at the time was 117, and today the result of the test is 5.3, and I have lost 20 kilograms. Does this mean that I have passed the pre-diabetic stage and have become a normal person?     2
How do I know that I have diabetes?                                                                                                                                                                                                                         2
What foods are beneficial for diabetics?                                                                                                                                                                                                                    2
What are the most important causes of diabetes?                                                                                                                                                                                                             2
Causes of diabetes                                                                                                                                                                                                                                          2
What is the treatment for parotitis?                                                                                                                                                                                                                        2
Symptoms of high blood sugar                                                                                                                                                                                                                                2
What are the symptoms of gestational diabetes?                                                                                                                                                                                                              2
What are normal blood sugar levels?                                                                                                                                                                                                                         2
What are the most important risk factors for developing type 1 diabetes?                                                                                                                                                                                    2
Peace be upon you. When I was 19 years old, I was treated for hypothyroidism. I took the medication leyvotirox50. Now my TSH is moderate. Now I am pregnant. I follow up with the endocrinologist. My questions...                                          2
Name: count, dtype: int64

In [15]:
question = "What are the symptoms of diabetes?"

result = df[df["Question"] == question]
result = pd.DataFrame(result)
print(result[["Question", "Answer", "Category"]].to_string(index=False))

                          Question                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Answer Category
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                The most important symptoms are frequent urination and excessive thirst. For more information, see diabetes in the dictionary. diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Weight loss, laziness, lethargy, frequent urination, thirst, dullness in the eyes, and pain in the body diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Diabetes in adults is usually non-specific and insidious, and its most important symptoms are: fatigue, fatigue, weight loss, frequent urination, especially at night, thirst, and difficulty healing boils. Sometimes it is not accidental.\nBut in children and young adults, it comes on quickly over several days to a few weeks: day and night polyuria. Polydipsia and dry mouth. Good appetite . weight loss . Fatigue and exhaustion. The injured person may experience an emergency condition and be admitted to the hospital immediately diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Drink plenty of water\nFrequent urination\nFeeling hungry diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              It is not necessary to have symptoms to diagnose the disease, and if they do exist, the most important of them is increased thirst and urination diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Symptoms of diabetes include frequent urination at night, increased thirst, and a sudden decrease in body weight diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           There are not necessarily symptoms, the most important of which, if present, is an increase in thirst and urination diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          A lot of urine\nFrequent thirst\nweight loss\nIt may be asymptomatic diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 There are many symptoms of diabetes, the most important of which are thirst, frequent urination, increased appetite for food, sometimes hunger, itchy skin, general weakness. diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              The most common symptoms of diabetes are excessive diarrhea, frequent urination, and feeling hungry\nThere are other less prominent symptoms, such as blurred vision, a feeling of weakness, leg pain, delayed wound healing, and itching.\nHere it must be noted that there is a large difference in the appearance and severity of these symptoms between patients and according to the type of diabetes. Some symptoms may be completely absent, or they may be minor and do not attract the attention of the affected person, and thus diagnosis is delayed.\nDue to the widespread spread of diabetes, a group of factors called risk factors have been identified, such as obesity, lack of physical activity, and a history of diabetes in the family. When these factors are present, blood sugar is analyzed even in the absence of the symptoms mentioned. See Diabetes in the dictionary.\nmy regards diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Symptoms do not necessarily exist, but if they do, they include thirst and increased urination diabetes
What are the symptoms of diabetes?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Symptoms do not necessarily exist, and if they do exist, the most important of them is an increase in thirst and urination diabetes

In [16]:
df = df.dropna(subset=["Question", "Answer"])

In [17]:
df["Question"] = df["Question"].astype(str).str.strip()
df["Answer"] = df["Answer"].astype(str).str.strip()
df["Category"] = df["Category"].astype(str).str.strip()

In [18]:
df

,Question,Answer,Category
6629,If the patient enters a diabetic coma and we d...,"Hyperglycemic coma does not occur suddenly, bu...",diabetes
12015,I suffer from dizziness and my blood sugar lev...,"Your safety, God willing. It may be normal due...",diabetes
14653,I am diabetic 2. I take Amaryl 2 ml before foo...,Glycosylated hemoglobin analysis is very impor...,diabetes
15283,"Age 54, normal blood pressure, weight 74, heig...",Who told you that taking B12 is not according ...,diabetes
20096,When I test my blood sugar after fasting for 7...,"Monitor your blood sugar in a laboratory, not ...",diabetes
...,...,...,...
808249,Can hirsutism be an obstacle to pregnancy sinc...,"Hirsutism can be a cause of contraception, but...",Endocrine diseases
808332,"In the name of God, the most gracious, the mos...",What you mentioned in your question constitute...,Endocrine diseases
808335,I have a sister who suffers from hyperthyroidi...,This medicine should not be used during pregna...,Endocrine diseases
808336,I was on duty at the hospital when a woman cam...,The condition goes away with the use of birth ...,Endocrine diseases
808350,Does a mild deficiency in the hormone thyroxin...,This is easy to find out by giving the infant ...,Endocrine diseases

In [19]:
df.duplicated().sum()

np.int64(8)

In [20]:
duplicates = df[df.duplicated(keep=False)]

print(duplicates.to_string(index=False))

                                                                                                                                                                                                                                               Question                                                                                                                                                                                                                                                                                                                           Answer           Category
                                                                                                                                                                                                                                     Diabetes treatment                                                                                                                                                                                                                   This requires an integrated nutritional and therapeutic system under the supervision of the treating physician           diabetes
                                                                                                                                                                                                                                     Diabetes treatment                                                                                                                                                                                                                   This requires an integrated nutritional and therapeutic system under the supervision of the treating physician           diabetes
                                                                                                                                                                                                                        The best treatment for diabetes                                                                                                                                                                                                                   This requires an integrated nutritional and therapeutic system under the supervision of the treating physician           diabetes
                                                                                                                                                                                                                             Useful fruit for diabetics                                                                                                                                                                                                                                                                                     Moderation in food is the basis of treatment           diabetes
                                                                                                                                                                                                                             Useful fruit for diabetics                                                                                                                                                                                                                                                                                     Moderation in food is the basis of treatment           diabetes
                                                                                                                                                                                                            What is the treatment for high blood sugar?                                                                                                                                                                                                                   This requires an integrated nutritional and therapeutic system under the supervision of the treating physician           diabetes
                                                                                                                                                                                                                        The best treatment for diabetes                                                                                                                                                                                                                   This requires an integrated nutritional and therapeutic system under the supervision of the treating physician           diabetes
                                                                                                                                                                                                            What is the treatment for high blood sugar?                                                                                                                                                                                                                   This requires an integrated nutritional and therapeutic system under the supervision of the treating physician           diabetes
                                                                                                                                                                                                                  What is the normal blood sugar level?                                                                                                                                                                                                                                                                 Fasting, less than 100 and two hours after eating, less than 140           diabetes
                                                                                                                                                                                                                  What is the normal blood sugar level?                                                                                                                                                                                                                                                                 Fasting, less than 100 and two hours after eating, less than 140           diabetes
    I used metformin to lose weight for four months. I was eating normally and I lost weight. I was increasing the dose up to 2000, but I feel that its effect is decreasing and the body has become resistant to it. What is the explanation for that?                                                                                                                                                                                                                                                                          Basically, you should reduce the amount of food you eat           diabetes
    I used metformin to lose weight for four months. I was eating normally and I lost weight. I was increasing the dose up to 2000, but I feel that its effect is decreasing and the body has become resistant to it. What is the explanation for that?                                                                                                                                                                                                                                                                          Basically, you should reduce the amount of food you eat           diabetes
                           My wife got pregnant after 9 months, knowing that I have been diabetic for 15 years and I am 35. I was treated with vitamin E for a period of time for my disease to affect pregnancy, and it took place after giving birth. The better your blood sugar control is, the more you will maintain the functions of your body’s organs, including sexual function\nA person with diabetes can marry and have children. Statistics may indicate lower chances of childbearing, but statistics are worthless when each case is evaluated individually.\nmy regards           diabetes
                           My wife got pregnant after 9 months, knowing that I have been diabetic for 15 years and I am 35. I was treated with vitamin E for a period of time for my disease to affect pregnancy, and it took place after giving birth. The better your blood sugar control is, the more you will maintain the functions of your body’s organs, including sexual function\nA person with diabetes can marry and have children. Statistics may indicate lower chances of childbearing, but statistics are worthless when each case is evaluated individually.\nmy regards           diabetes
A cumulative blood sugar test 3 months ago was 6.3, and my weight at the time was 117, and today the result of the test is 5.3, and I have lost 20 kilograms. Does this mean that I have passed the pre-diabetic stage and have become a normal person?                                                                                                                                                                                                                                                            Yes, I have passed the pre-diabetic stage. Persevere in losing weight Endocrine diseases
A cumulative blood sugar test 3 months ago was 6.3, and my weight at the time was 117, and today the result of the test is 5.3, and I have lost 20 kilograms. Does this mean that I have passed the pre-diabetic stage and have become a normal person?                                                                                                                                                                                                                                                            Yes, I have passed the pre-diabetic stage. Persevere in losing weight Endocrine diseases

In [21]:
df.drop_duplicates(inplace=True)

In [22]:
def clean_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Normalize Unicode
    text = unicodedata.normalize("NFKC", text)

    # Replace escaped newlines/tabs
    text = text.replace("\\n", " ")
    text = text.replace("\\t", " ")

    # Replace real newlines and tabs with spaces
    text = re.sub(r"[\r\n\t]+", " ", text)

    # Remove control characters
    text = "".join(
        char for char in text
        if unicodedata.category(char) not in ["Cc", "Cf"]
        or char in ["\n", "\t"]
    )

    # Normalize different quotation marks
    text = text.replace("“", '"')
    text = text.replace("”", '"')
    text = text.replace("‘", "'")
    text = text.replace("’", "'")

    # Normalize multiple spaces
    text = re.sub(r"\s+", " ", text)

    # Remove spaces before punctuation
    text = re.sub(r"\s+([,.!?;:])", r"\1", text)

    # Remove spaces around parentheses
    text = re.sub(r"\(\s+", "(", text)
    text = re.sub(r"\s+\)", ")", text)

    return text.strip()

In [127]:
df["Question"] = df["Question"].apply(clean_text)
df["Answer"] = df["Answer"].apply(clean_text)
df["Category"] = df["Category"].apply(clean_text)